services:
  # FRONTEND (React + Vite)
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
      args:
        - VITE_API_URL=${API_URL}
        - VITE_REVERB_APP_KEY=tyazklael8i55u4u8d1q
        - VITE_REVERB_HOST=${DOMAIN}
        - VITE_REVERB_PORT=8080 
        - VITE_REVERB_SCHEME=http 
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - chaos-inc-net

  # BACKEND (Laravel)
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
        DB_DATABASE: ${MYSQL_DATABASE}
        DB_USERNAME: ${MYSQL_USER}
        DB_PASSWORD: ${MYSQL_PASSWORD}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        APP_URL: ${API_URL}
        FRONTEND_URL: ${FRONTEND_URL}
        # SESSION_DOMAIN: ${DOMAIN} # En un despliege real, hay que poner aqui el dominio del a web.
        SANCTUM_STATEFUL_DOMAINS: "${DOMAIN},localhost:5173,127.0.0.1:5173,localhost,127.0.0.1"
    command: ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - chaos-inc-net

  # CONEXIÓN (Reverb)
  reverb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    ports:
      - "8080:8080"
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      APP_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      # SESSION_DOMAIN: ${DOMAIN} # En un despliege real, hay que poner aqui el dominio del a web.
      SANCTUM_STATEFUL_DOMAINS: "${DOMAIN},localhost:5173,127.0.0.1:5173,localhost,127.0.0.1"
    networks:
      - chaos-inc-net

  # TRABAJADOR DE COLAS
  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    command: php artisan queue:work --tries=3 --timeout=90 --memory=128 --sleep=1
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      APP_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      # SESSION_DOMAIN: ${DOMAIN} # En un despliege real, hay que poner aqui el dominio del a web.
      SANCTUM_STATEFUL_DOMAINS: "${DOMAIN},localhost:5173,127.0.0.1:5173,localhost,127.0.0.1"
    networks:
      - chaos-inc-net
    deploy:
      replicas: 3

  # PLANIFICADOR DE TAREAS
  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    command: php artisan schedule:work
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
      backend:
        condition: service_started
    env_file:
      - ./backend/.env
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      APP_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      # SESSION_DOMAIN: ${DOMAIN} # En un despliege real, hay que poner aqui el dominio del a web.
      SANCTUM_STATEFUL_DOMAINS: "${DOMAIN},localhost:5173,127.0.0.1:5173,localhost,127.0.0.1"
    networks:
      - chaos-inc-net

  # BASE DE DATOS (MySQL)
  mysql:
    image: mysql:8.0
    container_name: chaosinc_db
    restart: always
    command: --log_bin_trust_function_creators=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chaos-inc-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5

  # CACHÉ/TIEMPO REAL (Redis)
  redis:
    image: valkey/valkey:8.0-alpine
    container_name: chaosinc_valkey
    restart: always
    command: >
      sh -c "valkey-server --requirepass ${REDIS_PASSWORD} & 
             sleep 2; 
             valkey-cli -a ${REDIS_PASSWORD} flushall; 
             wait"
    ports:
      - "6379:6379"
    networks:
      - chaos-inc-net

networks:
  chaos-inc-net:
    driver: bridge

volumes:
  db_data:
