FROM oven/bun:1.2-alpine

WORKDIR /app

COPY package.json bun.lock* ./

RUN bun install

# Solo copia el código, node_modules ya está en la capa anterior
COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev", "--host"]