# Construcción con Bun
FROM oven/bun:1.2-alpine AS builder

WORKDIR /app

# Copiar solo los archivos de dependencias primero para aprovechar el caché de Docker
COPY ./frontend/package.json ./frontend/bun.lock* ./
RUN bun install --frozen-lockfile

# Copiar el resto del código del frontend
COPY ./frontend .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Compilar la aplicación 
RUN bun run build

# Servidor de Producción con Nginx
FROM nginx:alpine

# Copiar la configuración personalizada de Nginx
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los archivos compilados 
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]